menu:
- {name: 'projects', url: '/projects'}
- {name: 'resume', url: '/cv'}
- {name: 'contact', url: '/contact'}


projects:
- {name: 'Nalo Mix Pro', type: 'APSC 101', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Differential Swerve Drive Module V1', type: 'Personal Project', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Differential Swerve Drive Module V2', type: 'VEX Project', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Differential Swerve Drive Module V3', type: 'VEX Project', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Beam Profile Monitor Actuator', type: 'RMTL Project', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Cold Trap', type: 'RMTL Project', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Ion Thruster', type: 'Chemistry, Grade 12', year: '2022', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Spring Launcher', type: 'Physics, Grade 12', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: '3D Printed DC Motor', type: 'Physics, Grade 11', year: '2021', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Nintendo Switch Apple Watch Charger', type: 'Etsy Product', year: '2022', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'AirTag Pokeball Keychain', type: 'Etsy Product', year: '2022', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}
- {name: 'Adjustable iPad Stand', type: 'Etsy Product', year: '2022', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'nalo_mix_pro-project_page'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jcgullberg'}
- {icon: 'twitter', link: 'https://www.printables.com/@jamescgullber_244830'}
- {icon: 'instagram', link: 'https://www.instagram.com/jamesgullberg/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/james-gullberg-8507b4201/'}

contacts:
- {name: 'James Gullberg', department: 'Mechatronics and Robotics Eng', institution: 'Queens University', location: 'Kingston, Ontario', phone: '+1 226 503 6841', email: 'j.c.gullberg@queensu.ca', image: 'assets/img/contact.jpg'}
