menu:
- {name: 'projects', url: '/projects'}
- {name: 'resume', url: '/cv'}
- {name: 'contact', url: '/contact'}


projects:
- {name: 'Nalo Mix Pro', year: '2023', info: 'bing bong' , image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jcgullberg'}
- {icon: 'twitter', link: 'https://www.printables.com/@jamescgullber_244830'}
- {icon: 'instagram', link: 'https://www.instagram.com/jamesgullberg/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/james-gullberg-8507b4201/'}

contacts:
- {name: 'James Gullberg', department: 'Mechatronics and Robotics Eng', institution: 'Queens University', location: 'Kingston, Ontario', phone: '+1 226 503 6841', email: 'j.c.gullberg@queensu.ca', image: 'assets/img/contact.jpg'}
